### ISSUE TITLE
[Question] Adding to $PATH

### ISSUE THREAD

**Issue by lonix1** [robertdebock/ansible-role-environment#1]
I want to add to the path, so I used the `PATH: "$PATH:/foo.bar"` example from the docs.

But that adds that exact string to `/etc/environment` (without expansion) and so breaks the path.

This is what I did:
````
- become: true
  block:
  - include_role: name=robertdebock.environment
    vars:
      environment_list:
        PATH: "$PATH:/foo.bar"
````

Am I doing this correctly?

environment:
- ubuntu 18.04
- ansible 2.8.4
